# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attendance.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(842, 673)
        self.btnLogin = QtWidgets.QPushButton(Dialog)
        self.btnLogin.setGeometry(QtCore.QRect(140, 210, 161, 32))
        self.btnLogin.setObjectName("btnLogin")
        self.lblAttendees = QtWidgets.QLabel(Dialog)
        self.lblAttendees.setGeometry(QtCore.QRect(580, 30, 111, 16))
        self.lblAttendees.setObjectName("lblAttendees")
        self.comboBoxClass = QtWidgets.QComboBox(Dialog)
        self.comboBoxClass.setGeometry(QtCore.QRect(60, 280, 340, 50))
        self.comboBoxClass.setMinimumSize(QtCore.QSize(340, 50))
        self.comboBoxClass.setMaximumSize(QtCore.QSize(340, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBoxClass.setFont(font)
        self.comboBoxClass.setEditable(False)
        self.comboBoxClass.setObjectName("comboBoxClass")
        self.comboBoxClass.addItem("")
        self.comboBoxClass.addItem("")
        self.comboBoxClass.addItem("")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 80, 341, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblUsername = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUsername.sizePolicy().hasHeightForWidth())
        self.lblUsername.setSizePolicy(sizePolicy)
        self.lblUsername.setObjectName("lblUsername")
        self.horizontalLayout.addWidget(self.lblUsername)
        self.txtUsername = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtUsername.setMinimumSize(QtCore.QSize(260, 30))
        self.txtUsername.setMaximumSize(QtCore.QSize(260, 30))
        self.txtUsername.setObjectName("txtUsername")
        self.horizontalLayout.addWidget(self.txtUsername)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 150, 341, 42))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblPassword = QtWidgets.QLabel(self.layoutWidget1)
        self.lblPassword.setEnabled(True)
        self.lblPassword.setMinimumSize(QtCore.QSize(70, 40))
        self.lblPassword.setMaximumSize(QtCore.QSize(70, 40))
        self.lblPassword.setObjectName("lblPassword")
        self.horizontalLayout_2.addWidget(self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txtPassword.setMinimumSize(QtCore.QSize(260, 30))
        self.txtPassword.setMaximumSize(QtCore.QSize(260, 30))
        self.txtPassword.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.txtPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.horizontalLayout_2.addWidget(self.txtPassword)
        self.btnSubmit = QtWidgets.QPushButton(Dialog)
        self.btnSubmit.setGeometry(QtCore.QRect(140, 580, 161, 32))
        self.btnSubmit.setObjectName("btnSubmit")
        self.tblAttendees = QtWidgets.QTableWidget(Dialog)
        self.tblAttendees.setGeometry(QtCore.QRect(440, 60, 391, 601))
        self.tblAttendees.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblAttendees.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblAttendees.setProperty("showDropIndicator", False)
        self.tblAttendees.setDragDropOverwriteMode(False)
        self.tblAttendees.setAlternatingRowColors(False)
        self.tblAttendees.setShowGrid(False)
        self.tblAttendees.setWordWrap(False)
        self.tblAttendees.setCornerButtonEnabled(False)
        self.tblAttendees.setObjectName("tblAttendees")
        self.tblAttendees.setColumnCount(4)
        self.tblAttendees.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblAttendees.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblAttendees.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttendees.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttendees.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttendees.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblAttendees.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblAttendees.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblAttendees.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblAttendees.setItem(0, 3, item)
        self.tblAttendees.verticalHeader().setVisible(False)
        self.btnLogout = QtWidgets.QPushButton(Dialog)
        self.btnLogout.setGeometry(QtCore.QRect(140, 620, 161, 32))
        self.btnLogout.setObjectName("btnLogout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(110, 340, 241, 76))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblClassStartTime = QtWidgets.QLabel(self.widget)
        self.lblClassStartTime.setObjectName("lblClassStartTime")
        self.horizontalLayout_3.addWidget(self.lblClassStartTime)
        self.txtClassStartTime = QtWidgets.QLabel(self.widget)
        self.txtClassStartTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtClassStartTime.setObjectName("txtClassStartTime")
        self.horizontalLayout_3.addWidget(self.txtClassStartTime)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblClassLateTime = QtWidgets.QLabel(self.widget)
        self.lblClassLateTime.setObjectName("lblClassLateTime")
        self.horizontalLayout_5.addWidget(self.lblClassLateTime)
        self.txtClassLateTime = QtWidgets.QLabel(self.widget)
        self.txtClassLateTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtClassLateTime.setObjectName("txtClassLateTime")
        self.horizontalLayout_5.addWidget(self.txtClassLateTime)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblClassEndTime = QtWidgets.QLabel(self.widget)
        self.lblClassEndTime.setObjectName("lblClassEndTime")
        self.horizontalLayout_4.addWidget(self.lblClassEndTime)
        self.txtClassEndTime = QtWidgets.QLabel(self.widget)
        self.txtClassEndTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtClassEndTime.setObjectName("txtClassEndTime")
        self.horizontalLayout_4.addWidget(self.txtClassEndTime)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnLogin.setText(_translate("Dialog", "Log into Blackboard"))
        self.lblAttendees.setText(_translate("Dialog", "List of Attendees"))
        self.comboBoxClass.setItemText(0, _translate("Dialog", "Select Class for Attendance"))
        self.comboBoxClass.setItemText(1, _translate("Dialog", "CS380 Python"))
        self.comboBoxClass.setItemText(2, _translate("Dialog", "CS450 Data Science for R"))
        self.lblUsername.setText(_translate("Dialog", "User Name"))
        self.lblPassword.setText(_translate("Dialog", "Password"))
        self.btnSubmit.setText(_translate("Dialog", "Submit Attendance"))
        item = self.tblAttendees.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tblAttendees.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Last Name"))
        item = self.tblAttendees.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "First Name"))
        item = self.tblAttendees.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "ID"))
        item = self.tblAttendees.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Timestamp"))
        __sortingEnabled = self.tblAttendees.isSortingEnabled()
        self.tblAttendees.setSortingEnabled(False)
        item = self.tblAttendees.item(0, 0)
        item.setText(_translate("Dialog", "Jex"))
        item = self.tblAttendees.item(0, 1)
        item.setText(_translate("Dialog", "Ryan"))
        item = self.tblAttendees.item(0, 2)
        item.setText(_translate("Dialog", "1003456"))
        item = self.tblAttendees.item(0, 3)
        item.setText(_translate("Dialog", "12:15 PM"))
        self.tblAttendees.setSortingEnabled(__sortingEnabled)
        self.btnLogout.setText(_translate("Dialog", "Log out"))
        self.lblClassStartTime.setText(_translate("Dialog", "Class Start Time"))
        self.txtClassStartTime.setText(_translate("Dialog", "12:20 PM"))
        self.lblClassLateTime.setText(_translate("Dialog", "Late Arrival Threshold"))
        self.txtClassLateTime.setText(_translate("Dialog", "    12:30 PM"))
        self.lblClassEndTime.setText(_translate("Dialog", "Class End Time"))
        self.txtClassEndTime.setText(_translate("Dialog", "   1:40 PM"))
